
User.create(email: "ajorjao13@gmail.com", password: "asdasd123", admin: "true")

#no mover el orden de las intolerancias
Intolerance.create(name: "lactosa", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: ["lactosa","lactose","leche","milk"])
# Intolerance.create(name: "gluten", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "mani", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "nueces", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
Intolerance.create(name: "apio", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: ["apio","apium","graviolens","celery"])
# Intolerance.create(name: "mostaza", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "huevo", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "sesamo", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "pescado", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "crustaceos", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "mariscos", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "soya", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
# Intolerance.create(name: "sulfitos", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: [])
Intolerance.create(name: "legumbres", minor_symptom: "", medium_symptom: "", major_symptom: "", key_components: ["legumbre","legume","lupinus albus","altramuz","altramuces","lupins","lupino"])

# Product.first.intolerances << Intolerance.first

#Company.create(id: , name: , url: "")

Company.create(id: 7802900295, name: "soprole", url: "http://www.soprole.cl/productos?page=1")
Company.create(id: 7801810, name: "lipton", url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
#Company.create(id: 78020000, name: "lays", url: "")
Company.create(id: , name: "Colun", url: "http://www.colun.cl/")
Company.create(id: , name: "Carte Dor 1", url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Hellsman" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Malloa" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "JB" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Dorina" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Maizena" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Bonella" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Club" , url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Banda Azul", url: "http://www.unileverfoodsolutions.cl/productos-marcas/marcas")
Company.create(id: , name: "Savory", url: "https://www.savory.cl/productos")
Company.create(id: , name: "Calan" , url: "http://www.calan.cl/productos/")
Company.create(id: , name: "Loncoleche", url: "http://www.loncoleche.cl/productos.html")
#Company.create(id: , name: "Costa" , url: "")
Company.create(id: , name: "Quaker" , url: "http://www.quaker.cl/?page_id=7649")
Company.create(id: , name: "Vivo" , url: "http://www.vivo.cl/")
#Company.create(id: , name: "Carozzi" , url: "")
Company.create(id: , name: "Deyco" , url: "http://www.deyco.cl/productos-deyco.html")
Company.create(id: , name: "Coca Cola", url: "http://www.cocacoladechile.cl/")
Company.create(id: , name: "Mundo San Jose" , url: "http://www.mundosanjose.cl/productos/")
#Company.create(id: , name: "Supremo" , url: "")
#Company.create(id: , name: "Kryspo" , url: "")
#Company.create(id: , name: "Ambrosoli" , url: "")
#Company.create(id: , name: "Sprim" , url: "")
#Company.create(id: , name: "Tratorri" , url: "")
#Company.create(id: , name: "Selecta" , url: "")
#Company.create(id: , name: "Miraflores" , url: "")
#Company.create(id: , name: "Maggi" , url: "")
#Company.create(id: , name: "Lucchetti" , url: "")
#Company.create(id: , name: "Caricia", url: "")


# Company.create(id: 780, name: "")
# Company.create(id: 780, name: "")
# Company.create(id: 780, name: "")